"""Fix metodo_pago field

Revision ID: 30998375cbb9
Revises: 5715a2fe9992
Create Date: 2025-11-29 17:49:05.019826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30998375cbb9'
down_revision = '5715a2fe9992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('metodo_pago',
               existing_type=mysql.ENUM('online', 'presencial', 'mixto', collation='utf8mb4_unicode_ci'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('metodo_pago',
               existing_type=mysql.ENUM('online', 'presencial', 'mixto', collation='utf8mb4_unicode_ci'),
               nullable=True)

    # ### end Alembic commands ###
