"""Initial migration

Revision ID: 808ae3f6e5a7
Revises: b6e3556a3ae2
Create Date: 2025-11-29 18:49:37.691155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808ae3f6e5a7'
down_revision = 'b6e3556a3ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad_personas', sa.Integer(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amenidades', sa.JSON(), nullable=True),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('cliente', 'trabajador', 'admin'), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_rut'), ['rut'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('numero_habitacion', sa.String(length=10), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'ocupada', 'limpieza', 'mantenimiento'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_habitacion')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('noches', sa.Integer(), nullable=False),
    sa.Column('precio_por_noche', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_servicios_extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmada', 'check_in_realizado', 'check_out_realizado', 'cancelada'), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas_especiales', sa.Text(), nullable=True),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_check_in_real', sa.DateTime(), nullable=True),
    sa.Column('fecha_check_out_real', sa.DateTime(), nullable=True),
    sa.Column('cancelado_por_id', sa.Integer(), nullable=True),
    sa.Column('check_in_realizado_por_id', sa.Integer(), nullable=True),
    sa.Column('check_out_realizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['check_in_realizado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['check_out_realizado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('rooms')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_rut'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('room_types')
    # ### end Alembic commands ###
