"""Fix metodo_pago to String

Revision ID: b6e3556a3ae2
Revises: 30998375cbb9
Create Date: 2025-11-29 18:00:20.420344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6e3556a3ae2'
down_revision = '30998375cbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('metodo_pago',
               existing_type=mysql.ENUM('online', 'presencial', 'mixto', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('metodo_pago',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('online', 'presencial', 'mixto', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
